# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# play nice with others
umask 002

# specify the One True Editor
export EDITOR=/usr/bin/vim

# various paths
# possibly break them out into per-machine local files
export CPATH=~/local/include:$CPATH

case $HOSTNAME in
    hugin) 
        export PATH=~/local/jdk-7/bin:~/local/glassfish3/bin:$PATH:~/local/android-sdk-linux/tools:~/local/android-sdk-linux/platform-tools
        export JAVA_HOME=~/local/jdk-7
        export ANDROID_HOME=~/local/android-sdk-linux
        ;;
    hapax)
        export JAVA_HOME=~/local/jdk-6
        export ANDROID_HOME=~/local/android-sdk-linux
        export PATH=~/local/android-sdk-linux/tools:~/local/jdk-6/bin:~/local/glassfish3/bin:~/local/apache-jmeter/bin:$PATH
        export PERL_LOCAL_LIB_ROOT="/home/nathan/perl5";
        export PERL_MB_OPT="--install_base /home/nathan/perl5";
        export PERL_MM_OPT="INSTALL_BASE=/home/nathan/perl5";
        export PERL5LIB="/home/nathan/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:/home/nathan/perl5/lib/perl5";
        export PATH="/home/nathan/perl5/bin:$PATH";
        ;;
    wintermute) 
        export JAVA_HOME=~/local/jdk-6
        export PATH=~/local/android-sdk-linux/tools:~/local/jdk-6/bin:$PATH
        #export PATH=~/hs/bin:~/local/arm-elf/bin:$PATH 
        ;;
esac

[ -d ~/.cabal/ ] && export PATH=~/.cabal/bin:$PATH
# maybe a function pathadd() to encapsulate the above pattern?
# pathcons, pathsnoc
# see https://github.com/jdevera/dotfiles/blob/master/bash.d/010_env_functions.sh
export PATH=~/bin:~/dotfiles/bin:$PATH:/var/lib/gems/1.8/bin
export PYTHONPATH=~/lib/python


######################################################################
# Interactive-Only Configuration Below This Point
[ -z "$PS1" ] && return

# ensure my personal tmp exists
[ -d ~/tmp/ ] || mkdir ~/tmp

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
[ -f /etc/bash_completion ] && . /etc/bash_completion

# don't put duplicate lines in the history. 
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth
export HISTIGNORE="[   ]*:&:bg:fg:exit"

### shell options
# see http://wiki.bash-hackers.org/internals/shell_options

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell

# don't overwrite .bash_history
shopt -s histappend

# TODO maybe enable this, be careful with other $PROMPT_COMMAND in .bash_prompt
# sync history between bashes http://briancarper.net/blog/248/
#export PROMPT_COMMAND="history -a; history -n"

shopt -s no_empty_cmd_completion
shopt -s shift_verbose
#shopt -s checkhash

# enable recursive globbing for **
shopt -s globstar

# disable annoying console beep
[ -x setterm ] && setterm -blength 0

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"
[ -x $HOME/bin/lesspipe.sh ] && eval "$($HOME/bin/lesspipe.sh)"
export LESS_ADVANCED_PREPROCESSOR=yes

# but prefer vimpager if available
if [[ -x $HOME/bin/vimpager ]]; then
    export PAGER=$HOME/bin/vimpager
    alias less=$PAGER
    alias zless=$PAGER
fi

if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
else
    # basic prompt fallback if we can't find the prompt script
    PS1='${prefix}\u@\h:\w\$ '
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# keychain ssh key management (non-interactive)
# TODO: just detect the files?  maybe keychain can auto-add.
if [ -x "$(which keychain 2> /dev/null)" ]; then  
    # i really need to clean up my key filenames...
    keychain --quiet --ignore-missing \
        ~/.ssh/id_rsa                 \
        ~/.ssh/id_dsa                 \
        ~/.ssh/github.id_dsa          \
        ~/.ssh/nathan_github.dsa      \
        ~/.ssh/id_dsa.xenkibbutz-new  \
        ~/.ssh/nathan-gitolite.dsa

        # ~/.ssh/id_dsa.xenkibbutz      

    . ~/.keychain/${HOSTNAME}-sh
fi

# automatically invoke screen if we're not in a session already
if [ -x `which screen` ] && [ "$TERM" != "screen" ] && [ "$DISPLAY" != ":0" ] && [ "$DISPLAY" != ":0.0" ]; then
    # -xRR will attach without detaching other sessions
    screen -xRR
fi

