# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

# use custom themes if found
if [[ -f "$ZSH/custom/themes/powerlevel10k/powerlevel10k.zsh-theme" ]]; then
    DEFAULT_USER=$USER
    #local nerdfonts=(~/.fonts/*Nerd*.ttf)
    #[[ ${#nerdfonts} > 0 ]] && \
        POWERLEVEL9K_MODE='nerdfont-complete'
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vi_mode context dir dir_writable vcs )
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs history time)
    POWERLEVEL9K_TIME_ICON=''
    #POWERLEVEL9K_VI_INSERT_MODE_STRING='∫'
    #POWERLEVEL9K_VI_COMMAND_MODE_STRING='∮'
    POWERLEVEL9K_VI_INSERT_MODE_STRING='δ'
    POWERLEVEL9K_VI_COMMAND_MODE_STRING='ℵ'
    POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='black'
    POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='green'
    POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='black'
    POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='yellow'
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='∫ '
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
    POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
    #POWERLEVEL9K_SHORTEN_DELIMITER=''
    POWERLEVEL9K_SHORTEN_DELIMITER=''
    ZSH_THEME="powerlevel10k/powerlevel10k"
elif [[ -f "$ZSH/custom/themes/ns.zsh-theme" ]]; then
    ZSH_THEME="ns"
else
    ZSH_THEME="ys"
fi

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"
# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"
# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"
# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13
# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true
# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"
# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"
# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# always be in tmux
ZSH_TMUX_AUTOSTART=true
# but don't start a fresh one if we've already got one
ZSH_TMUX_AUTOSTART_ONCE=true
# reattach to any existing session if possible
ZSH_TMUX_AUTOCONNECT=true
# keep zsh alive after tmux exit
ZSH_TMUX_AUTOQUIT=false
#ZSH_TMUX_FIXTERM=true


# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    vi-mode
    z
    git
    jsontools
    urltools
    tmux
    #spring
    #dircycle
    #oc
)

[[ "$ZSH_THEME" != "powerlevel10k/powerlevel10k" ]] && plugins+=(timer)
(($+commands[keychain])) && plugins+=(keychain)
(($+commands[asadmin])) && plugins+=(glassfish)

zstyle :omz:plugins:keychain agents ssh
zstyle :omz:plugins:keychain identities id_rsa 
zstyle :omz:plugins:keychain options --quiet --ignore-missing

source $ZSH/oh-my-zsh.sh
source ~/.bash_aliases

# prefix a path onto $PATH if it exists
cons_path() { 
    [[ -d "$1" ]] && export PATH="$1:$PATH" 
}

cons_path /var/lib/gems/1.8/bin
cons_path ~/local/slic3r/bin
cons_path ~/local/perl5/bin
cons_path ~/local/apache-jmeter/bin
cons_path ~/local/idea/bin
cons_path ~/local/glassfish3/bin
cons_path ~/local/arduino
cons_path ~/local/android-studio/bin
cons_path ~/local/android-sdk-linux/tools
cons_path ~/local/android-sdk-linux/platform-tools
cons_path ~/local/racket/bin
cons_path ~/local/rust/bin
cons_path ~/local/node/bin
cons_path ~/local/emacs/bin
cons_path ~/.cabal/bin
cons_path $JAVA_HOME/bin
cons_path ~/.local/bin
cons_path ~/dotfiles/bin
cons_path ~/bin

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# manual oc completion
alias zoc='source <(oc completion zsh)'
